### ISSUE TITLE
<nil> on messages.getConversationMembers in conversation

### ISSUE THREAD

**Issue by h1ew** [stek29/vk#1]
Доброго времени суток!

Пытаюсь вызвать метод
`messages, _ :=
vkapi.Messages{client}.GetConversationMembers(vkapi.MessagesGetConversationMembersParams{
					PeerID: from,
				})`

В личных сообщениях получаю все данные, но в беседах получаю `<nil>,` у бота есть доступ к сообщениям, есть админка, в Long Poll API выставлена версия 5.80.

**Comment by stek29** [comment]
Извините, что так долго отвечал.

Что если сделать `messages, err := ...`, и вывести `err`?
